---
name: CI
on: [ push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://lpenz/omnilint:v0.2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ghaction-python-stdeb
      - uses: actions/checkout@v2
        with:
          repository: lpenz/ftpsmartsync
          path: ftpsmartsync
      - uses: ./ghaction-python-stdeb
        with:
          working_directory: ftpsmartsync
      - name: check debian packages
        run: |
          set -e -x
          dpkg --info ftpsmartsync/*.deb
          dpkg --contents ftpsmartsync/*.deb
  dockerhub:
    needs: [ omnilint, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        if: steps.version.outputs.version_tagged != ''
        with:
          push: true
          tags: ${{ github.repository }}:${{ steps.version.outputs.version_tagged }}

